### ISSUE TITLE
Run DGM in single process

### ISSUE THREAD

**Issue by jviereck** [machines-in-motion/dynamic_graph_manager#14]
Right now DGM requires a multi-process setup. To make testing / debugging easier, I think it would be good to have a single process implementation. My hope is we get this for free when the current single-class setup is separated into multiple classes (e.g. for the hardware and the control process).

**Comment by MaximilienNaveau** [comment]
I do agree

**Comment by MaximilienNaveau** [comment]
I forgot to mention that despite the fact that it has not been really tested you can create a single process with dynamic_graph_manager already...
The main of the robot has to be a bit change. Instead of using run, there is a "run_single_process()"
Which does exactly what you want.
It will spawn a single real time thread which does everything.
